<?php header('Content-type: text/html; charset=utf-8'); ?>
<?php echo $this->doctype('HTML5');?>
<html>
<head>
<?php echo $this->headTitle("Bookmark Management System");?>
<?php

echo $this->headLink ()->appendStylesheet ( $this->baseUrl ( 'css/common.css' ) )->appendStylesheet ( $this->baseUrl ( 'libs/JQueryUi/css/jqueryui.smoothness.custom.css' ) )->appendStylesheet ( $this->baseUrl ( 'libs/JQueryTools/css/jquery.tools.css' ) )->appendStylesheet ( $this->baseUrl ( 'libs/Prompt/css/prompt.css' ) )->appendStylesheet ( $this->baseUrl ( 'libs/Clock/css/clock.css' ) );

echo $this->headScript ()->prependFile ( $this->baseUrl ( "libs/Facebook/js/all.js" ) )->prependFile ( $this->baseUrl ( "libs/Resize/js/jquery.resize.min.js" ) )->prependFile ( $this->baseUrl ( "libs/Touchslider/js/touchslider.min.js" ) )->prependFile ( $this->baseUrl ( "libs/Lodash/js/lodash.min.js" ) )->prependFile ( $this->baseUrl ( "libs/Clock/js/clock.js" ) )->prependFile ( $this->baseUrl ( "libs/Prompt/js/prompt.js" ) )->prependFile ( $this->baseUrl ( "libs/JQueryUi/js/jqueryui.smoothness.min.js" ) )->prependFile ( $this->baseUrl ( "libs/JQueryTools/js/jquery.tools.min.js" ) )->prependFile ( $this->baseUrl ( "libs/BlockUI/jquery.blockUI.js" ) )->prependFile ( $this->baseUrl ( "libs/AjaxFileUpload/js/ajaxfileupload.js" ) )->prependFile ( $this->baseUrl ( "libs/Jquery/js/jquery-1.8.1.min.js" ) )->prependFile ( $this->baseUrl ( 'libs/Html5/js/html5.js' ), 'text/javascript', array (
		'conditional' => 'lt IE 9' 
) );
?>
</head>
<body>
	<!-- FB Share Initialize -->
	<div id='fb-root'></div>
	<!-- <script src='http://connect.facebook.net/en_US/all.js'></script> -->
	<script type="text/javascript">
    	//<![CDATA[
		window.fbAsyncInit = function() {
			FB.init({
				appId  : '179414048860819',
				//status : true, // check login status
				cookie : true, // enable cookies to allow the server to access the session
				xfbml  : true, // parse XFBML
				loggin : true
			});
			// Sharing in Facebook
    		/*FB.ui({
        		method: 'feed',
        		display: 'dialog',
        		link: "<?php echo urlencode($this->serverUrl().$this->url());?>",
        		name: "Ownhp",
        		caption: 'The Facebook Connect JavaScript SDK',
      	      	description: (
      	      		'A small JavaScript library that allows you to harness ' +
      	      		'the power of Facebook, bringing the user\'s identity, ' +
      	      		'social graph and distribution power to your site.'
      	   		),
        		description: "This is a worderfull app to go with"
        	},
        	function(response) {
        		if (response && response.post_id) {
        			//alert('Post was published.');
        		} else {
        			//alert('Post was not published.');
        		}
        	});*/

        	// Login with FB
			/*FB.login(function(response) {
				if (response.authResponse) {
					alert('Welcome!  Fetching your information.... ');
					FB.api('/me', function(response) {
						alert('Good to see you, ' + response.name + '.');
					});
				} else {
					alert('User cancelled login or did not fully authorize.');
				}
			},{scope : "user_about_me,email,manage_notifications"});
			*/
		}
		// Loading FacebookSDK Asynchronously
		(function(d){
			var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
			if (d.getElementById(id)) {return;}
			js = d.createElement('script'); js.id = id; js.async = true;
			js.src = "//connect.facebook.net/en_US/all.js";
			ref.parentNode.insertBefore(js, ref);
		}(document));
		 
		//]]>
    </script>
	<div id="wrapper">
		<header id="header">
			<aside>
				<!-- Displaying Logo -->
				<a id="logo" href="<?php echo $this->baseUrl("/")?>"
					title="Return to Home-Page"> <img
					src="<?php echo $this->baseUrl("images/logo.png")?>"
					alt="Bookmark Management" />
				</a>
				<!-- Displaying Clock -->
				<div id="clock">
					<div id="Clock_Date"></div>
					<ul>
						<li id="hours"></li>
						<li class="point">:</li>
						<li id="min"></li>
						<li class="point">:</li>
						<li id="sec"></li>
					</ul>
				</div>

				<nav id="top-nav">
					<ul>
					</ul>
				</nav>
			</aside>
			<div style="clear: both;"></div>
		</header>
		<!-- #header-->

		<div style="clear: both;"></div>
		<div id="content">
    		<?php echo $this->layout ()->content; ?>
    		<br style="clear: both" />
		</div>
		<!-- #content-->
		<footer id="footer">&copy; by Atyantik Technologies 2012</footer>
		<!-- #footer -->
	</div>
	<!-- #wrapper -->
</body>
</html>