<?php header('Content-type: text/html; charset=utf-8'); ?>
<?php echo $this->doctype('HTML5');?>
<html>
<head>
<?php echo $this->headTitle("Bookmark Management System");?>
<?php

echo $this->headLink ()
->appendStylesheet ( $this->baseUrl ( 'css/common.css' ) )
->appendStylesheet ( $this->baseUrl ( 'libs/JQueryUi/css/jqueryui.smoothness.custom.css' ) )
->appendStylesheet ( $this->baseUrl ( 'libs/JQueryTools/css/jquery.tools.css' ) )
->appendStylesheet ( $this->baseUrl ( 'libs/Prompt/css/prompt.css' ) )
->appendStylesheet ( $this->baseUrl ( 'libs/Clock/css/clock.css' ) );

echo $this->headScript ()
->prependFile ( $this->baseUrl ( "libs/Facebook/js/all.js" ) )
->prependFile ( $this->baseUrl ( "libs/Resize/js/jquery.resize.min.js" ) )
->prependFile ( $this->baseUrl ( "libs/Touchslider/js/touchslider.min.js" ) )
->prependFile ( $this->baseUrl ( "libs/Lodash/js/lodash.min.js" ) )
->prependFile ( $this->baseUrl ( "libs/Clock/js/clock.js" ) )
->prependFile ( $this->baseUrl ( "libs/Prompt/js/prompt.js" ) )
->prependFile ( $this->baseUrl ( "libs/JQueryUi/js/jqueryui.smoothness.min.js" ) )
->prependFile ( $this->baseUrl ( "libs/JQueryTools/js/jquery.tools.min.js" ) )
->prependFile ( $this->baseUrl ( "libs/BlockUI/jquery.blockUI.js" ) )
->prependFile ( $this->baseUrl ( "libs/AjaxFileUpload/js/ajaxfileupload.js" ) )
->prependFile ( $this->baseUrl ( "libs/Jquery/js/jquery-1.8.0.min.js" ) )
->prependFile ( $this->baseUrl ( 'libs/Html5/js/html5.js' ), 'text/javascript', array ('conditional' => 'lt IE 9') );
?>
</head>
<body>
	<!-- FB Share Initialize -->
	<div id='fb-root'></div>
    <!-- <script src='http://connect.facebook.net/en_US/all.js'></script> -->
    <script type="text/javascript">
    	//<![CDATA[
		window.fbAsyncInit = function() {
			FB.init({
				appId  : '179414048860819',
				status : true, // check login status
				cookie : true, // enable cookies to allow the server to access the session
				xfbml  : true  // parse XFBML
			});
			// Sharing in Facebook
    		/*FB.ui({
        		method: 'feed',
        		display: 'dialog',
        		link: "<?php echo urlencode($this->serverUrl().$this->url());?>",
        		name: "Ownhp",
        		description: "This is a worderfull app to go with"
        	},
        	function(response) {
        		if (response && response.post_id) {
        			//alert('Post was published.');
        		} else {
        			//alert('Post was not published.');
        		}
        	});
        	*/
		}
		//]]>
    </script>
	<div id="wrapper">
		<header id="header">
			<aside>
				<!-- Displaying Logo -->
				<a id="logo" href="<?php echo $this->baseUrl("/")?>"
					title="Return to Home-Page"> <img
					src="<?php echo $this->baseUrl("images/logo.png")?>"
					alt="Bookmark Management" />
				</a>
				<!-- Displaying Clock -->
				<div id="clock">
					<div id="Clock_Date"></div>
					<ul>
						<li id="hours"></li>
						<li class="point">:</li>
						<li id="min"></li>
						<li class="point">:</li>
						<li id="sec"></li>
					</ul>
				</div>
				
				<nav id="top-nav">
					<ul>
					</ul>
				</nav>
			</aside>
			<div style="clear: both;"></div>
		</header>
		<!-- #header-->

		<div style="clear: both;"></div>
		<div id="content">
    		<?php echo $this->layout ()->content; ?>
    		<br style="clear: both" />
		</div>
		<!-- #content-->
		<footer id="footer">&copy; by Atyantik Technologies 2012</footer>
		<!-- #footer -->
	</div>
	<!-- #wrapper -->
</body>
</html>