<?php header('Content-type: text/html; charset=utf-8'); ?>
<?php echo $this->doctype('HTML5');?>
<html>
<head>
<?php echo $this->headTitle();?>
<?php echo $this->headLink()
					->appendStylesheet($this->baseUrl('css/style.css'))
					->appendStylesheet($this->baseUrl('css/reset.css'))
					->appendStylesheet($this->baseUrl('css/structure.css'))
					->appendStylesheet($this->baseUrl('css/jquery.tools.css'));
?>
<?php echo $this->headScript()
		->appendFile($this->baseUrl('libs/html5/html5.js'),'text/javascript', array('conditional' => 'lt IE 9'))
		->appendFile($this->baseUrl('js/jquery-1.8.0.min.js'))
		->appendFile($this->baseUrl('js/jquery.tools.min.js'));
?>
</head>
<body>
	<?php
	echo $this->layout ()->content;
	?>
</body>
</html>