<div id="divUserLogin">
	<form id="<?php echo $this->element->getId();?>"
		action="<?php echo $this->element->getAction();?>"
		method="<?php echo $this->element->getMethod();?>"
		enctype="<?php echo $this->element->getEnctype()?>">
		<table class="zend_form">
			<tbody>
				<tr>
					<td><?php echo $this->element->username->renderLabel();?></td>
					<td><?php echo $this->element->username->renderViewHelper();?></td>
				</tr>
				<tr>
					<td><?php echo $this->element->password->renderLabel();?></td>
					<td><?php echo $this->element->password->renderViewHelper();?></td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>
						<?php
							echo $this->element->submit->renderViewHelper();
							echo $this->element->reset->renderViewHelper();
						?>
					</td>
					<td>&nbsp;</td>
				</tr>
			</tbody>
		</table>
	</form>
</div>